---
language: cpp
compiler:
  - gcc
  - clang
install:
  - sudo apt-get install -y mercurial libegl1-mesa-dev libgl1-mesa-dev libx11-xcb-dev libxcb-composite0-dev libxcb-util0-dev libxcb-res0-dev libxcb-ewmh-dev libxcb-keysyms1-dev libxcb-xfixes0-dev
  - hg clone https://hg.libsdl.org/SDL
  - cd SDL
  - hg up release-2.0.4
  - ./configure
  - make -j$(nproc)
  - sudo make install
script:
  - ./numake
  - bin/xveearr --version
sudo: required
dist: trusty
