#!/bin/sh

DESC=$(git describe --long 2> /dev/null | sed 's/\([^-]*-g\)/r\1/;s/-/./g')
if [ -z "${DESC}" ]; then
	printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"
else
	printf "%s" "${DESC}"
fi
